require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  
Metrics/ClassLength:
  Max: 100
  
Metrics/MethodLength:
  Max: 20
